name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
        run: |
          set -x

          docker version      
        # run: |
        #   sudo apt-get update
        #   sudo apt upgrade
        #   sudo apt --fix-broken install

        #   sudo apt-get -y install docker.io    

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and Test Dependencies
        run: |
          docker build -t lambda-layer .
          docker run --rm -v $PWD:/app lambda-layer bash /app/build-dependencies.sh

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Test with pytest
        run: |
          pip install pytest
          pytest

      - name: Deploy to AWS
        run: |
          npm install -g aws-cdk
          cdk deploy

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
